version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: earthquakedb
      POSTGRES_USER: earthquake
      POSTGRES_PASSWORD: rumble
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
