global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "Health check"
    metrics_path: "/api/health-check"
    scheme: "https"
    static_configs:
      - targets: ["earthquake-insights-chi.vercel.app"]
    scrape_interval: 15s
    scrape_timeout: 15s
