apiVersion: apps/v1
kind: Deployment
metadata:
  name: earthquake-insights
  labels:
    app: earthquake-insights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earthquake-insights
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: earthquake-insights
    spec:
      containers:
        - name: earthquake-insights
          image: earthquake-insights:test
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: earthquake-insights-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: earthquake-insights
